
  create table "public"."absences" (
    "id" uuid not null default gen_random_uuid(),
    "employee_id" uuid not null,
    "start_date" date not null,
    "end_date" date,
    "reason" text,
    "message" text,
    "status" text not null default 'pending'::text,
    "submitted_at" timestamp with time zone default now()
      );


alter table "public"."absences" enable row level security;


  create table "public"."app_settings" (
    "id" integer not null,
    "email_notifications" boolean not null default true,
    "admin_notification_emails" text[] not null default '{}'::text[],
    "absence_requests" boolean not null default true,
    "schedule_changes" boolean not null default true,
    "employee_updates" boolean not null default false,
    "system_updates" boolean not null default false,
    "daily_digest" boolean not null default false,
    "digest_time" text not null default '08:00'::text,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."app_settings" enable row level security;


  create table "public"."employee_notifications" (
    "id" uuid not null default gen_random_uuid(),
    "employee_id" uuid,
    "type" text not null,
    "title" text not null,
    "message" text not null,
    "priority" text not null default 'low'::text,
    "is_read" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."employee_notifications" enable row level security;


  create table "public"."employees" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "email" text,
    "department" text,
    "is_active" boolean not null default true,
    "created_at" timestamp without time zone default now(),
    "auth_user_id" uuid,
    "role" text default 'employee'::text
      );


alter table "public"."employees" enable row level security;


  create table "public"."mail_jobs" (
    "id" bigint generated by default as identity not null,
    "type" text not null,
    "payload" jsonb not null,
    "status" text not null default 'queued'::text,
    "attempt_count" integer not null default 0,
    "last_error" text,
    "created_at" timestamp with time zone not null default now(),
    "processed_at" timestamp with time zone,
    "job_key" text generated always as (
CASE
    WHEN (type = 'admin_new_absence'::text) THEN (((((payload ->> 'employee_id'::text) || '|'::text) || (payload ->> 'start_date'::text)) || '|'::text) || COALESCE((payload ->> 'end_date'::text), ''::text))
    ELSE NULL::text
END) stored
      );


alter table "public"."mail_jobs" enable row level security;


  create table "public"."notifications" (
    "id" uuid not null default gen_random_uuid(),
    "type" text not null,
    "title" text not null,
    "message" text not null,
    "created_at" timestamp with time zone not null default now(),
    "is_read" boolean not null default false
      );


alter table "public"."notifications" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "is_admin" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
      );



  create table "public"."shift_change_requests" (
    "id" uuid not null default gen_random_uuid(),
    "employee_id" uuid,
    "target_employee_id" uuid,
    "current_shift_date" date not null,
    "requested_shift_date" date not null,
    "reason" text,
    "message" text,
    "status" text not null default 'pending'::text,
    "submitted_at" timestamp with time zone not null default now()
      );


alter table "public"."shift_change_requests" enable row level security;


  create table "public"."shift_publications" (
    "id" uuid not null default gen_random_uuid(),
    "start_date" date not null,
    "end_date" date not null,
    "published_at" timestamp with time zone not null default now(),
    "status" text not null default 'pending'::text
      );



  create table "public"."shifts" (
    "id" uuid not null default gen_random_uuid(),
    "employee_id" uuid not null,
    "work_date" date not null,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "type" text not null default 'normal'::text,
    "is_locked" boolean not null default false,
    "note" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "published" boolean not null default false,
    "published_at" timestamp with time zone,
    "minutes" integer not null default 0
      );


alter table "public"."shifts" enable row level security;


  create table "public"."time_off_requests" (
    "id" uuid not null default gen_random_uuid(),
    "employee_id" uuid,
    "start_date" date not null,
    "end_date" date not null,
    "reason" text,
    "message" text,
    "status" text not null default 'pending'::text,
    "submitted_at" timestamp with time zone not null default now()
      );


alter table "public"."time_off_requests" enable row level security;


  create table "public"."time_periods" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "start_date" date not null,
    "end_date" date not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."time_periods" enable row level security;

CREATE UNIQUE INDEX absences_pkey ON public.absences USING btree (id);

CREATE UNIQUE INDEX app_settings_pkey ON public.app_settings USING btree (id);

CREATE UNIQUE INDEX employee_notifications_pkey ON public.employee_notifications USING btree (id);

CREATE UNIQUE INDEX employees_email_lower_uq ON public.employees USING btree (lower(email)) WHERE (email IS NOT NULL);

CREATE UNIQUE INDEX employees_email_unique ON public.employees USING btree (email);

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (id);

CREATE UNIQUE INDEX employees_user_id_unique ON public.employees USING btree (auth_user_id);

CREATE INDEX idx_absences_emp_dates ON public.absences USING btree (employee_id, start_date, end_date);

CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at DESC);

CREATE INDEX idx_notifications_is_read ON public.notifications USING btree (is_read);

CREATE INDEX idx_shifts_emp_date_pub ON public.shifts USING btree (employee_id, work_date, published);

CREATE INDEX idx_shifts_employee_id ON public.shifts USING btree (employee_id);

CREATE INDEX idx_shifts_published ON public.shifts USING btree (published);

CREATE INDEX idx_shifts_work_date ON public.shifts USING btree (work_date);

CREATE INDEX mail_jobs_emp_queued_idx ON public.mail_jobs USING btree (((payload ->> 'employee_id'::text))) WHERE (status = 'queued'::text);

CREATE UNIQUE INDEX mail_jobs_job_key_unique ON public.mail_jobs USING btree (job_key);

CREATE UNIQUE INDEX mail_jobs_pkey ON public.mail_jobs USING btree (id);

CREATE INDEX mail_jobs_queued_time_type_idx ON public.mail_jobs USING btree (created_at, type) WHERE (status = 'queued'::text);

CREATE INDEX mail_jobs_status_idx ON public.mail_jobs USING btree (status) WHERE (status = 'queued'::text);

CREATE UNIQUE INDEX mail_jobs_unique_key ON public.mail_jobs USING btree (job_key) WHERE (type = 'admin_new_absence'::text);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX shift_change_requests_pkey ON public.shift_change_requests USING btree (id);

CREATE UNIQUE INDEX shift_publications_pkey ON public.shift_publications USING btree (id);

CREATE UNIQUE INDEX shifts_employee_id_work_date_key ON public.shifts USING btree (employee_id, work_date);

CREATE UNIQUE INDEX shifts_pkey ON public.shifts USING btree (id);

CREATE UNIQUE INDEX time_off_requests_pkey ON public.time_off_requests USING btree (id);

CREATE UNIQUE INDEX time_periods_pkey ON public.time_periods USING btree (id);

CREATE UNIQUE INDEX uniq_emp_date_update ON public.employee_notifications USING btree (employee_id, type, message);

alter table "public"."absences" add constraint "absences_pkey" PRIMARY KEY using index "absences_pkey";

alter table "public"."app_settings" add constraint "app_settings_pkey" PRIMARY KEY using index "app_settings_pkey";

alter table "public"."employee_notifications" add constraint "employee_notifications_pkey" PRIMARY KEY using index "employee_notifications_pkey";

alter table "public"."employees" add constraint "employees_pkey" PRIMARY KEY using index "employees_pkey";

alter table "public"."mail_jobs" add constraint "mail_jobs_pkey" PRIMARY KEY using index "mail_jobs_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."shift_change_requests" add constraint "shift_change_requests_pkey" PRIMARY KEY using index "shift_change_requests_pkey";

alter table "public"."shift_publications" add constraint "shift_publications_pkey" PRIMARY KEY using index "shift_publications_pkey";

alter table "public"."shifts" add constraint "shifts_pkey" PRIMARY KEY using index "shifts_pkey";

alter table "public"."time_off_requests" add constraint "time_off_requests_pkey" PRIMARY KEY using index "time_off_requests_pkey";

alter table "public"."time_periods" add constraint "time_periods_pkey" PRIMARY KEY using index "time_periods_pkey";

alter table "public"."absences" add constraint "absences_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE not valid;

alter table "public"."absences" validate constraint "absences_employee_id_fkey";

alter table "public"."absences" add constraint "absences_status_valid_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text]))) not valid;

alter table "public"."absences" validate constraint "absences_status_valid_check";

alter table "public"."app_settings" add constraint "app_settings_id_check" CHECK ((id = 1)) not valid;

alter table "public"."app_settings" validate constraint "app_settings_id_check";

alter table "public"."employee_notifications" add constraint "employee_notifications_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE not valid;

alter table "public"."employee_notifications" validate constraint "employee_notifications_employee_id_fkey";

alter table "public"."employee_notifications" add constraint "uniq_emp_date_update" UNIQUE using index "uniq_emp_date_update";

alter table "public"."employees" add constraint "employees_email_unique" UNIQUE using index "employees_email_unique";

alter table "public"."employees" add constraint "employees_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'employee'::text]))) not valid;

alter table "public"."employees" validate constraint "employees_role_check";

alter table "public"."employees" add constraint "employees_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."employees" validate constraint "employees_user_id_fkey";

alter table "public"."employees" add constraint "employees_user_id_unique" UNIQUE using index "employees_user_id_unique";

alter table "public"."employees" add constraint "fk_employees_auth" FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."employees" validate constraint "fk_employees_auth";

alter table "public"."mail_jobs" add constraint "mail_jobs_job_key_unique" UNIQUE using index "mail_jobs_job_key_unique";

alter table "public"."notifications" add constraint "notifications_type_check" CHECK ((type = ANY (ARRAY['absence_request'::text, 'absence_approved'::text, 'absence_declined'::text, 'employee_added'::text, 'shift_auto'::text]))) not valid;

alter table "public"."notifications" validate constraint "notifications_type_check";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."shift_change_requests" add constraint "shift_change_requests_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE not valid;

alter table "public"."shift_change_requests" validate constraint "shift_change_requests_employee_id_fkey";

alter table "public"."shift_change_requests" add constraint "shift_change_requests_target_employee_id_fkey" FOREIGN KEY (target_employee_id) REFERENCES employees(id) not valid;

alter table "public"."shift_change_requests" validate constraint "shift_change_requests_target_employee_id_fkey";

alter table "public"."shifts" add constraint "shifts_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE not valid;

alter table "public"."shifts" validate constraint "shifts_employee_id_fkey";

alter table "public"."shifts" add constraint "shifts_employee_id_work_date_key" UNIQUE using index "shifts_employee_id_work_date_key";

alter table "public"."shifts" add constraint "shifts_time_order_chk" CHECK (((start_time IS NULL) OR (end_time IS NULL) OR (start_time < end_time))) not valid;

alter table "public"."shifts" validate constraint "shifts_time_order_chk";

alter table "public"."shifts" add constraint "shifts_type_allowed_chk" CHECK ((type = ANY (ARRAY['normal'::text, 'locked'::text, 'absent'::text, 'holiday'::text]))) not valid;

alter table "public"."shifts" validate constraint "shifts_type_allowed_chk";

alter table "public"."shifts" add constraint "shifts_type_check" CHECK ((type = ANY (ARRAY['normal'::text, 'locked'::text, 'absent'::text, 'holiday'::text]))) not valid;

alter table "public"."shifts" validate constraint "shifts_type_check";

alter table "public"."time_off_requests" add constraint "time_off_requests_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE not valid;

alter table "public"."time_off_requests" validate constraint "time_off_requests_employee_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.claim_employee_jobs(p_employee_id text, p_since timestamp with time zone, p_types text[], p_limit integer DEFAULT 200)
 RETURNS SETOF mail_jobs
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with candidate as (
    select id
    from public.mail_jobs
    where status = 'queued'
      and created_at >= p_since
      and type = any(p_types)
      and payload->>'employee_id' = p_employee_id
    order by created_at asc
    limit p_limit
  ),
  locked as (
    update public.mail_jobs m
      set status = 'processing',
          processed_at = now(),
          attempt_count = m.attempt_count + 1
    where m.id in (select id from candidate)
      and m.status = 'queued'
    returning m.*
  )
  select * from locked;
$function$
;

CREATE OR REPLACE FUNCTION public.claim_employee_jobs(p_employee_id uuid, p_since timestamp with time zone, p_types text[], p_limit integer DEFAULT 200)
 RETURNS SETOF mail_jobs
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  return query
  with cte as (
    select id
    from mail_jobs
    where status = 'queued'
      and (payload->>'employee_id') = p_employee_id::text
      and type = any(p_types)
      and created_at >= p_since
    order by created_at asc
    limit p_limit
    for update skip locked
  )
  update mail_jobs m
  set status = 'processing'
  from cte
  where m.id = cte.id
  returning m.*;
end;
$function$
;

CREATE OR REPLACE FUNCTION public."current_role"()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  select current_setting('role');
$function$
;

CREATE OR REPLACE FUNCTION public.delete_shifts(_employee_id uuid, _dates date[])
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  delete from public.shifts
  where employee_id = _employee_id
    and work_date = any(_dates);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_admin_new_absence()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  cfg RECORD;
  _end_date date;
BEGIN
  SELECT email_notifications, absence_requests, admin_notification_emails
    INTO cfg
  FROM public.app_settings
  WHERE id = 1;

  IF COALESCE(cfg.email_notifications,false) IS NOT TRUE THEN RETURN NEW; END IF;
  IF COALESCE(cfg.absence_requests,false)     IS NOT TRUE THEN RETURN NEW; END IF;
  IF cfg.admin_notification_emails IS NULL
     OR array_length(cfg.admin_notification_emails,1) < 1 THEN
    RETURN NEW;
  END IF;

  -- normalisoi: jos end_date puuttuu → start_date
  _end_date := COALESCE(NEW.end_date, NEW.start_date);

  INSERT INTO public.mail_jobs (type, status, attempt_count, payload)
  VALUES (
    'admin_new_absence',
    'queued',
    0,
    jsonb_build_object(
      'employee_id', NEW.employee_id,
      'start_date', NEW.start_date,
      'end_date',   _end_date,
      'reason',     NEW.reason
    )
  )
  ON CONFLICT (job_key) DO NOTHING;  -- nyt toimii, koska on UNIQUE CONSTRAINT

  -- älä kaada inserttiä vaikka HTTP failaa
  BEGIN
    PERFORM net.http_post(
      url     := 'https://musrmpblsazxcrhwthtc.functions.supabase.co/mailer',
      headers := jsonb_build_object('Authorization','Bearer '||'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11c3JtcGJsc2F6eGNyaHd0aHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjI3NzIsImV4cCI6MjA3MTQzODc3Mn0.k6zU1Eiif-06XVvlHMugfxsL-ZFnXiTuf5Qg28r5x8A'),
      body    := '{}'::jsonb
    );
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_employee_new_shift()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_employee_shift_changed()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if new.published is distinct from old.published
     and new.work_date  is not distinct from old.work_date
     and new.start_time is not distinct from old.start_time
     and new.end_time   is not distinct from old.end_time
     and new.type       is not distinct from old.type
     and new.minutes    is not distinct from old.minutes then
    return new;
  end if;

  if (new.work_date  is distinct from old.work_date
      or new.start_time is distinct from old.start_time
      or new.end_time   is distinct from old.end_time
      or new.type       is distinct from old.type
      or new.minutes    is distinct from old.minutes) then
    insert into public.employee_notifications (employee_id, type, title, message, created_at, is_read, priority)
    values (new.employee_id,
            'schedule_updated',
            'Työvuorosi on muuttunut',
            'Päivämäärä: ' || new.work_date::text,
            now(), false, 'medium')
    on conflict do nothing;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_employee_shift_deleted()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF OLD.published IS TRUE THEN
    -- sähköposti
    INSERT INTO public.mail_jobs(type, payload)
    VALUES ('employee_shift_deleted', jsonb_build_object(
      'employee_id', OLD.employee_id,
      'work_date',   OLD.work_date::text,
      'start',       OLD.start_time::text,
      'end',         OLD.end_time::text
    ));

    -- notifikaatio
    INSERT INTO public.employee_notifications (employee_id, type, title, message, created_at, is_read, priority)
    VALUES (
      OLD.employee_id,
      'shift_declined',
      'Vuorosi on peruttu',
      'Päivämäärä: ' || OLD.work_date::text,
      now(),
      FALSE,
      'medium'
    );
  END IF;
  RETURN OLD;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_on_publish_flip()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_shift_publication_jobs()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN NULL;
END;
$function$
;

create or replace view "public"."latest_publications_overview" as  SELECT sp.id AS publication_id,
    sp.start_date,
    sp.end_date,
    sp.status AS publication_status,
    count(j.*) FILTER (WHERE (j.status = 'queued'::text)) AS jobs_queued,
    count(j.*) FILTER (WHERE (j.status = 'processing'::text)) AS jobs_processing,
    count(j.*) FILTER (WHERE (j.status = 'sent'::text)) AS jobs_sent
   FROM (shift_publications sp
     LEFT JOIN mail_jobs j ON ((((((j.payload ->> 'work_date'::text))::date >= sp.start_date) AND (((j.payload ->> 'work_date'::text))::date <= sp.end_date)) AND (j.type = 'shift_publication'::text))))
  GROUP BY sp.id, sp.start_date, sp.end_date, sp.status
  ORDER BY sp.start_date DESC;


CREATE OR REPLACE FUNCTION public.notify_absence_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.notifications(type, title, message)
  values (
    'absence_request',
    'Uusi poissaolopyyntö',
    'Työntekijä ' || coalesce((select name from public.employees e where e.id = new.employee_id), 'Tuntematon')
      || ' on jättänyt poissaolopyynnön ' || new.start_date::text
      || coalesce(' – ' || new.end_date::text, '')
  );
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.notify_absence_status_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.status is distinct from old.status then
    if new.status = 'approved' then
      insert into public.notifications(type, title, message)
      values (
        'absence_approved',
        'Poissaolo hyväksytty',
        'Poissaolo ('|| new.start_date::text || coalesce(' – '||new.end_date::text,'') || ') hyväksyttiin.'
      );
    elsif new.status = 'declined' then
      insert into public.notifications(type, title, message)
      values (
        'absence_declined',
        'Poissaolo hylätty',
        'Poissaolopyyntö hylättiin.'
      );
    end if;
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.notify_employee_added()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.notifications(type, title, message)
  values (
    'employee_added',
    'Uusi työntekijä',
    coalesce(new.name,'Tuntematon') || ' on lisätty järjestelmään.'
  );
  return new;
end $function$
;

create or replace view "public"."publication_jobs_debug" as  SELECT sp.id AS publication_id,
    sp.start_date,
    sp.end_date,
    sp.status AS publication_status,
    j.id AS job_id,
    j.status AS job_status,
    j.created_at AS job_created,
    j.processed_at AS job_processed,
    (j.payload ->> 'employee_id'::text) AS employee_id,
    (j.payload ->> 'work_date'::text) AS work_date
   FROM (shift_publications sp
     LEFT JOIN mail_jobs j ON ((((((j.payload ->> 'work_date'::text))::date >= sp.start_date) AND (((j.payload ->> 'work_date'::text))::date <= sp.end_date)) AND (j.type = 'shift_publication'::text))))
  ORDER BY sp.start_date DESC, j.created_at DESC;


CREATE OR REPLACE FUNCTION public.publish_shifts(_start_date date, _end_date date)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE public.shifts
  SET published = true, published_at = now()
  WHERE work_date BETWEEN _start_date AND _end_date
    AND published = false;

  INSERT INTO public.shift_publications (start_date, end_date, status)
  VALUES (_start_date, _end_date, 'pending');

  INSERT INTO public.employee_notifications (employee_id, type, title, message, created_at, is_read, priority)
  SELECT DISTINCT s.employee_id,
         'schedule_published',
         'Uusi aikataulu julkaistu',
         'Tarkista uudet työvuorosi.',
         now(), false, 'high'
  FROM public.shifts s
  WHERE s.work_date BETWEEN _start_date AND _end_date
    AND s.published = true
    AND s.published_at >= now() - interval '1 minute';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end; $function$
;

CREATE OR REPLACE FUNCTION public.trg_absence_enqueue_job()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  insert into mail_jobs (type, payload)
  values (
    'admin_new_absence',
    jsonb_build_object(
      'absence_id', new.id,
      'employee_id', new.employee_id,
      'start_date', new.start_date,
      'end_date', new.end_date,
      'reason', new.reason
    )
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.unpublish_shifts(_start_date date, _end_date date)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.shifts
  set published = false
  where work_date between _start_date and _end_date;

  update public.shift_publications
  set status = 'canceled'
  where start_date = _start_date
    and end_date = _end_date;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_shifts(_employee_id uuid, _work_date date, _type text, _minutes integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  insert into public.shifts (employee_id, work_date, type, minutes)
  values (_employee_id, _work_date, _type, _minutes)
  on conflict (employee_id, work_date)
  do update set
    type = excluded.type,
    minutes = excluded.minutes;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_shifts_bulk(_rows jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  insert into shifts (employee_id, work_date, type, minutes)
  select (r->>'employee_id')::uuid,
         (r->>'work_date')::date,
         r->>'type',
         (r->>'minutes')::int
  from jsonb_array_elements(_rows) as r
  on conflict (employee_id, work_date)
  do update set type = excluded.type,
                minutes = excluded.minutes;
end;
$function$
;

grant select on table "public"."absences" to "anon";

grant delete on table "public"."absences" to "authenticated";

grant insert on table "public"."absences" to "authenticated";

grant references on table "public"."absences" to "authenticated";

grant select on table "public"."absences" to "authenticated";

grant trigger on table "public"."absences" to "authenticated";

grant truncate on table "public"."absences" to "authenticated";

grant update on table "public"."absences" to "authenticated";

grant delete on table "public"."absences" to "service_role";

grant insert on table "public"."absences" to "service_role";

grant references on table "public"."absences" to "service_role";

grant select on table "public"."absences" to "service_role";

grant trigger on table "public"."absences" to "service_role";

grant truncate on table "public"."absences" to "service_role";

grant update on table "public"."absences" to "service_role";

grant delete on table "public"."app_settings" to "service_role";

grant insert on table "public"."app_settings" to "service_role";

grant references on table "public"."app_settings" to "service_role";

grant select on table "public"."app_settings" to "service_role";

grant trigger on table "public"."app_settings" to "service_role";

grant truncate on table "public"."app_settings" to "service_role";

grant update on table "public"."app_settings" to "service_role";

grant delete on table "public"."employee_notifications" to "anon";

grant insert on table "public"."employee_notifications" to "anon";

grant references on table "public"."employee_notifications" to "anon";

grant select on table "public"."employee_notifications" to "anon";

grant trigger on table "public"."employee_notifications" to "anon";

grant truncate on table "public"."employee_notifications" to "anon";

grant update on table "public"."employee_notifications" to "anon";

grant delete on table "public"."employee_notifications" to "authenticated";

grant insert on table "public"."employee_notifications" to "authenticated";

grant references on table "public"."employee_notifications" to "authenticated";

grant select on table "public"."employee_notifications" to "authenticated";

grant trigger on table "public"."employee_notifications" to "authenticated";

grant truncate on table "public"."employee_notifications" to "authenticated";

grant update on table "public"."employee_notifications" to "authenticated";

grant delete on table "public"."employee_notifications" to "service_role";

grant insert on table "public"."employee_notifications" to "service_role";

grant references on table "public"."employee_notifications" to "service_role";

grant select on table "public"."employee_notifications" to "service_role";

grant trigger on table "public"."employee_notifications" to "service_role";

grant truncate on table "public"."employee_notifications" to "service_role";

grant update on table "public"."employee_notifications" to "service_role";

grant select on table "public"."employees" to "anon";

grant delete on table "public"."employees" to "authenticated";

grant insert on table "public"."employees" to "authenticated";

grant references on table "public"."employees" to "authenticated";

grant select on table "public"."employees" to "authenticated";

grant trigger on table "public"."employees" to "authenticated";

grant truncate on table "public"."employees" to "authenticated";

grant update on table "public"."employees" to "authenticated";

grant delete on table "public"."employees" to "service_role";

grant insert on table "public"."employees" to "service_role";

grant references on table "public"."employees" to "service_role";

grant select on table "public"."employees" to "service_role";

grant trigger on table "public"."employees" to "service_role";

grant truncate on table "public"."employees" to "service_role";

grant update on table "public"."employees" to "service_role";

grant delete on table "public"."mail_jobs" to "service_role";

grant insert on table "public"."mail_jobs" to "service_role";

grant references on table "public"."mail_jobs" to "service_role";

grant select on table "public"."mail_jobs" to "service_role";

grant trigger on table "public"."mail_jobs" to "service_role";

grant truncate on table "public"."mail_jobs" to "service_role";

grant update on table "public"."mail_jobs" to "service_role";

grant select on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."shift_change_requests" to "anon";

grant insert on table "public"."shift_change_requests" to "anon";

grant references on table "public"."shift_change_requests" to "anon";

grant select on table "public"."shift_change_requests" to "anon";

grant trigger on table "public"."shift_change_requests" to "anon";

grant truncate on table "public"."shift_change_requests" to "anon";

grant update on table "public"."shift_change_requests" to "anon";

grant delete on table "public"."shift_change_requests" to "authenticated";

grant insert on table "public"."shift_change_requests" to "authenticated";

grant references on table "public"."shift_change_requests" to "authenticated";

grant select on table "public"."shift_change_requests" to "authenticated";

grant trigger on table "public"."shift_change_requests" to "authenticated";

grant truncate on table "public"."shift_change_requests" to "authenticated";

grant update on table "public"."shift_change_requests" to "authenticated";

grant delete on table "public"."shift_change_requests" to "service_role";

grant insert on table "public"."shift_change_requests" to "service_role";

grant references on table "public"."shift_change_requests" to "service_role";

grant select on table "public"."shift_change_requests" to "service_role";

grant trigger on table "public"."shift_change_requests" to "service_role";

grant truncate on table "public"."shift_change_requests" to "service_role";

grant update on table "public"."shift_change_requests" to "service_role";

grant delete on table "public"."shift_publications" to "anon";

grant insert on table "public"."shift_publications" to "anon";

grant references on table "public"."shift_publications" to "anon";

grant select on table "public"."shift_publications" to "anon";

grant trigger on table "public"."shift_publications" to "anon";

grant truncate on table "public"."shift_publications" to "anon";

grant update on table "public"."shift_publications" to "anon";

grant delete on table "public"."shift_publications" to "authenticated";

grant insert on table "public"."shift_publications" to "authenticated";

grant references on table "public"."shift_publications" to "authenticated";

grant select on table "public"."shift_publications" to "authenticated";

grant trigger on table "public"."shift_publications" to "authenticated";

grant truncate on table "public"."shift_publications" to "authenticated";

grant update on table "public"."shift_publications" to "authenticated";

grant delete on table "public"."shift_publications" to "service_role";

grant insert on table "public"."shift_publications" to "service_role";

grant references on table "public"."shift_publications" to "service_role";

grant select on table "public"."shift_publications" to "service_role";

grant trigger on table "public"."shift_publications" to "service_role";

grant truncate on table "public"."shift_publications" to "service_role";

grant update on table "public"."shift_publications" to "service_role";

grant select on table "public"."shifts" to "anon";

grant delete on table "public"."shifts" to "authenticated";

grant insert on table "public"."shifts" to "authenticated";

grant references on table "public"."shifts" to "authenticated";

grant select on table "public"."shifts" to "authenticated";

grant trigger on table "public"."shifts" to "authenticated";

grant truncate on table "public"."shifts" to "authenticated";

grant update on table "public"."shifts" to "authenticated";

grant delete on table "public"."shifts" to "service_role";

grant insert on table "public"."shifts" to "service_role";

grant references on table "public"."shifts" to "service_role";

grant select on table "public"."shifts" to "service_role";

grant trigger on table "public"."shifts" to "service_role";

grant truncate on table "public"."shifts" to "service_role";

grant update on table "public"."shifts" to "service_role";

grant delete on table "public"."time_off_requests" to "anon";

grant insert on table "public"."time_off_requests" to "anon";

grant references on table "public"."time_off_requests" to "anon";

grant select on table "public"."time_off_requests" to "anon";

grant trigger on table "public"."time_off_requests" to "anon";

grant truncate on table "public"."time_off_requests" to "anon";

grant update on table "public"."time_off_requests" to "anon";

grant delete on table "public"."time_off_requests" to "authenticated";

grant insert on table "public"."time_off_requests" to "authenticated";

grant references on table "public"."time_off_requests" to "authenticated";

grant select on table "public"."time_off_requests" to "authenticated";

grant trigger on table "public"."time_off_requests" to "authenticated";

grant truncate on table "public"."time_off_requests" to "authenticated";

grant update on table "public"."time_off_requests" to "authenticated";

grant delete on table "public"."time_off_requests" to "service_role";

grant insert on table "public"."time_off_requests" to "service_role";

grant references on table "public"."time_off_requests" to "service_role";

grant select on table "public"."time_off_requests" to "service_role";

grant trigger on table "public"."time_off_requests" to "service_role";

grant truncate on table "public"."time_off_requests" to "service_role";

grant update on table "public"."time_off_requests" to "service_role";

grant delete on table "public"."time_periods" to "anon";

grant insert on table "public"."time_periods" to "anon";

grant references on table "public"."time_periods" to "anon";

grant select on table "public"."time_periods" to "anon";

grant trigger on table "public"."time_periods" to "anon";

grant truncate on table "public"."time_periods" to "anon";

grant update on table "public"."time_periods" to "anon";

grant delete on table "public"."time_periods" to "authenticated";

grant insert on table "public"."time_periods" to "authenticated";

grant references on table "public"."time_periods" to "authenticated";

grant select on table "public"."time_periods" to "authenticated";

grant trigger on table "public"."time_periods" to "authenticated";

grant truncate on table "public"."time_periods" to "authenticated";

grant update on table "public"."time_periods" to "authenticated";

grant delete on table "public"."time_periods" to "service_role";

grant insert on table "public"."time_periods" to "service_role";

grant references on table "public"."time_periods" to "service_role";

grant select on table "public"."time_periods" to "service_role";

grant trigger on table "public"."time_periods" to "service_role";

grant truncate on table "public"."time_periods" to "service_role";

grant update on table "public"."time_periods" to "service_role";


  create policy "admin_insert_absences"
  on "public"."absences"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_select_all_absences"
  on "public"."absences"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_absences"
  on "public"."absences"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "employee_insert_own_absences"
  on "public"."absences"
  as permissive
  for insert
  to authenticated
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "employee_select_own_absences"
  on "public"."absences"
  as permissive
  for select
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "employee_update_own_absences"
  on "public"."absences"
  as permissive
  for update
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))))
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "admin_insert_app_settings"
  on "public"."app_settings"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_app_settings"
  on "public"."app_settings"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "select_app_settings_all"
  on "public"."app_settings"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Employees view their own notifications"
  on "public"."employee_notifications"
  as permissive
  for select
  to public
using ((auth.uid() = employee_id));



  create policy "admin_insert_notifications"
  on "public"."employee_notifications"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_select_all_notifications"
  on "public"."employee_notifications"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_notifications"
  on "public"."employee_notifications"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "employee_select_own_notifications"
  on "public"."employee_notifications"
  as permissive
  for select
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "employee_update_own_notifications"
  on "public"."employee_notifications"
  as permissive
  for update
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))))
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "admin_insert_employees"
  on "public"."employees"
  as permissive
  for insert
  to authenticated
with check (((role = 'admin'::text) AND (auth_user_id = auth.uid())));



  create policy "admin_select_all_employees"
  on "public"."employees"
  as permissive
  for select
  to authenticated
using (((role = 'admin'::text) AND (auth_user_id = auth.uid())));



  create policy "admin_update_employees"
  on "public"."employees"
  as permissive
  for update
  to authenticated
using (((role = 'admin'::text) AND (auth_user_id = auth.uid())))
with check (((role = 'admin'::text) AND (auth_user_id = auth.uid())));



  create policy "dev: employees select for anon"
  on "public"."employees"
  as permissive
  for select
  to anon
using (true);



  create policy "employee_select_employees"
  on "public"."employees"
  as permissive
  for select
  to authenticated
using (true);



  create policy "employee_select_self"
  on "public"."employees"
  as permissive
  for select
  to authenticated
using ((auth_user_id = auth.uid()));



  create policy "employee_update_self"
  on "public"."employees"
  as permissive
  for update
  to authenticated
using ((auth_user_id = auth.uid()))
with check ((auth_user_id = auth.uid()));



  create policy "employees delete"
  on "public"."employees"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "employees_select_auth"
  on "public"."employees"
  as permissive
  for select
  to authenticated
using (true);



  create policy "dev: notifications select for anon"
  on "public"."notifications"
  as permissive
  for select
  to anon
using (true);



  create policy "dev_read_notifications_anon"
  on "public"."notifications"
  as permissive
  for select
  to anon
using (true);



  create policy "notifications insert"
  on "public"."notifications"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "notifications select"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using (true);



  create policy "notifications update"
  on "public"."notifications"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "notifications_select_auth"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Employees manage their own shift change requests"
  on "public"."shift_change_requests"
  as permissive
  for all
  to public
using ((auth.uid() = employee_id))
with check ((auth.uid() = employee_id));



  create policy "admin_insert_shift_changes"
  on "public"."shift_change_requests"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_select_all_shift_changes"
  on "public"."shift_change_requests"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_shift_changes"
  on "public"."shift_change_requests"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "employee_insert_own_shift_change"
  on "public"."shift_change_requests"
  as permissive
  for insert
  to authenticated
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "employee_select_own_shift_changes"
  on "public"."shift_change_requests"
  as permissive
  for select
  to authenticated
using (((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))) OR (target_employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid())))));



  create policy "employee_update_own_shift_change"
  on "public"."shift_change_requests"
  as permissive
  for update
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))))
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "admin_insert_shifts"
  on "public"."shifts"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_select_all_shifts"
  on "public"."shifts"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_shifts"
  on "public"."shifts"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "allow anon insert shifts"
  on "public"."shifts"
  as permissive
  for insert
  to anon
with check (true);



  create policy "allow anon shifts access"
  on "public"."shifts"
  as permissive
  for all
  to anon
using (true)
with check (true);



  create policy "allow anon update shifts"
  on "public"."shifts"
  as permissive
  for update
  to anon
using (true)
with check (true);



  create policy "anon delete shifts"
  on "public"."shifts"
  as permissive
  for delete
  to anon
using (true);



  create policy "anon insert shifts"
  on "public"."shifts"
  as permissive
  for insert
  to anon
with check (true);



  create policy "anon select shifts"
  on "public"."shifts"
  as permissive
  for select
  to anon
using (true);



  create policy "anon update shifts"
  on "public"."shifts"
  as permissive
  for update
  to anon
using (true)
with check (true);



  create policy "employee_select_own_shifts"
  on "public"."shifts"
  as permissive
  for select
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "shifts_select_auth"
  on "public"."shifts"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Employees manage their own time off requests"
  on "public"."time_off_requests"
  as permissive
  for all
  to public
using ((auth.uid() = employee_id))
with check ((auth.uid() = employee_id));



  create policy "admin_insert_time_off"
  on "public"."time_off_requests"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_select_all_time_off"
  on "public"."time_off_requests"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_time_off"
  on "public"."time_off_requests"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "employee_insert_own_time_off"
  on "public"."time_off_requests"
  as permissive
  for insert
  to authenticated
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "employee_select_own_time_off"
  on "public"."time_off_requests"
  as permissive
  for select
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "employee_update_own_time_off"
  on "public"."time_off_requests"
  as permissive
  for update
  to authenticated
using ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))))
with check ((employee_id IN ( SELECT e.id
   FROM employees e
  WHERE (e.auth_user_id = auth.uid()))));



  create policy "admin_insert_time_periods"
  on "public"."time_periods"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "admin_update_time_periods"
  on "public"."time_periods"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM employees e
  WHERE ((e.auth_user_id = auth.uid()) AND (e.role = 'admin'::text)))));



  create policy "select_time_periods_all"
  on "public"."time_periods"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER trg_absence_enqueue_job AFTER INSERT ON public.absences FOR EACH ROW EXECUTE FUNCTION trg_absence_enqueue_job();

CREATE TRIGGER trg_admin_new_absence AFTER INSERT ON public.absences FOR EACH ROW EXECUTE FUNCTION enqueue_admin_new_absence();

CREATE TRIGGER trg_notify_absence_insert AFTER INSERT ON public.absences FOR EACH ROW EXECUTE FUNCTION notify_absence_insert();

CREATE TRIGGER trg_notify_absence_update AFTER UPDATE ON public.absences FOR EACH ROW EXECUTE FUNCTION notify_absence_status_update();

CREATE TRIGGER trg_notify_employee_added AFTER INSERT ON public.employees FOR EACH ROW EXECUTE FUNCTION notify_employee_added();

CREATE TRIGGER trg_employee_shift_changed AFTER UPDATE ON public.shifts FOR EACH ROW WHEN ((new.employee_id IS NOT NULL)) EXECUTE FUNCTION enqueue_employee_shift_changed();

CREATE TRIGGER trg_employee_shift_deleted AFTER DELETE ON public.shifts FOR EACH ROW EXECUTE FUNCTION enqueue_employee_shift_deleted();

CREATE TRIGGER trg_shifts_updated_at BEFORE UPDATE ON public.shifts FOR EACH ROW EXECUTE FUNCTION set_updated_at();


